### ISSUE TITLE
read only .py file

### ISSUE THREAD

**Issue by The-real-decoder** [Cameron-Programer/Firefly#3]
you need to fix this

**Comment by Cameron-Programer** [comment]
Im going to need a bit more info than that to fix something

**Comment by The-real-decoder** [comment]
the pyhon file is a read only file therefore i cant point it in the way of the HTML file
and you allreaddy know this

**Comment by Cameron-Programer** [comment]
> 
> 
> the pyhon file is a read only file therefore i cant point it in the way of the HTML file
> and you allreaddy know this

kk all i got from you was "you need to fix this"

**Comment by Cameron-Programer** [comment]
The read only file is to stop it from being edited without credit 
Code is on the Repo if you want to edit it
